### PR TITLE
Add CI based on GitHub Actions and Badges

### PR DESCRIPTION
**Pull request by jhwgh1968**
Since I am making major changes, and the testing is currently manual, I thought I'd add this before going much further.

It doesn't do everything, but it should be a good starting point if you want to improve it.

### CODE REVIEW

**Comment by jhwgh1968** [comment]
Somehow, I didn't notice you had Travis CI already. :facepalm: 

If you'd like to switch [given the state that product is in](https://www.reddit.com/r/programming/comments/atjltu/layoffs_at_travis_ci_their_team_was_being/), feel free. Otherwise, you can close this PR.

**Comment by jhwgh1968** [comment]
Alright, I think it's ready to go!

In addition to getting everything that your Travis CI did, I also added clippy in warning-only mode. As you fix things, you can start switching thing to deny in order to have CI enforce them.

Because of the in-between state things are in right now, the CI will not trigger on this PR. But here is what it will look like, minus the `rustfmt` adjustments I made:

https://github.com/jhwgh1968/warc/actions/runs/200819003

Also, I added badges! (The "build status" badge will be fixed once this merges.)

https://github.com/jhwgh1968/warc/blob/master/README.md

**Comment by jedireza** [comment]
Rad. Now that you're a collaborator can you merge?

**Comment by jhwgh1968** [comment]
Indeed I can! :smile:

**Comment by jhwgh1968** [comment]
@jedireza, I did look into the config in Travis CI, and I don't have permission disable it for that project. Only you can turn it off. I think that might be necessary to make sure future PRs do the right thing.

If you log into Travis, click on your user in the northeast corner, and go to settings, you can "switch off" all the Git repos you control.

**Comment by jedireza** [comment]
I logged into Travis and disabled it for this repo. I also went through the repo settings and I cleared up anything referring to Travis.

I noticed there is a busted badge image on the readme:

Screen Shot 2020-08-08 at 5 32 30 PM

**Comment by jhwgh1968** [comment]
I figured that out, and have a PR open now.

**Pull request merged**
