### PR TITLE
New API for Record (Split Body and Headers)

### PR DESCRIPTION
**Pull request by jhwgh1968**
This is still in draft, because I've not gotten all the details nailed down nor the streams implemented. However, it's dramatic enough that it's worth an early review to get feedback on the approach.

### CODE REVIEW

**Review by jedireza — APPROVED** [review]
Pardon the delayed review. Thanks for the good commit messages!

Instead of simply looking at the whole diff at once, I stepped through each of the commits and associated diff and got a better appreciation for the work you've done.

I like it. I don't have much for critiques at this point. I like the naming choices you've made and where the API design is going. And the new functionality is rad.

Feel free to land the code and follow up with future PRs. Your call.

**Comment by jhwgh1968** [comment]
Thanks!

I want make sure this design will "fit together" with my re-write of streams first. There are some tricky parts in there with generics.

Once I do that, I will release it from Draft.

**Comment by jhwgh1968** [comment]
At long last, this is ready for review @jedireza!

**Comment by jedireza** [comment]
What a time to be alive! Looks great.

Thanks for the bit-sized well written commits, tests and examples. :shipit: 🚀

**Pull request merged**
